name: e2e test
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    paths-ignore:
      - '**.md'
      - '**.png'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.png'
jobs:
  job_1:
    name: e2e test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Go build
        run: |
          go build .
          go install .
      - name: Use goc to build self
        run: |
          ./goc build -o ./gocc .
      - name: run e2e test
        run: |
          go get github.com/onsi/ginkgo/ginkgo
          make e2e