name: e2e test
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  job_1:
    name: Build goc binary
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Go build
        run: |
          cd cmd/goc
          go build
      - name: Upload binary result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: goc
          path: cmd/goc/goc

  job_2:
    name: E2E test
    needs: job_1
    strategy:
      matrix:
        go-version: [1.13.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download built binary
        uses: actions/download-artifact@v1
        with:
          name: goc
      - name: Prepare test env
        run: |
          mv goc /usr/local/bin/
          go env -w GO111MODULE="auto"
      - name: Do test
        run: |
          cd tests/samples/simple_project
          goc build